# Generated by Django 5.0.7 on 2024-07-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('json', models.JSONField()),
                ('filters', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('keywords', models.ManyToManyField(to='blog.keyword')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.profile')),
            ],
        ),
        migrations.AddField(
            model_name='keyword',
            name='keyword_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.keyworddata'),
        ),
    ]
