# Generated by Django 5.0.7 on 2024-07-16 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('security', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIUsed',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('json', models.JSONField()),
                ('filters', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APICostRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('api_used', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.apiused')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('keywords', models.ManyToManyField(blank=True, to='blog.keyword')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.profile')),
            ],
        ),
    ]
