# Generated by Django 5.0.7 on 2024-07-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_keyword_profile_keyword_added_keyword_country_and_more'),
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='added',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='country',
        ),
        migrations.RemoveField(
            model_name='keyword',
            name='json',
        ),
        migrations.CreateModel(
            name='KeywordData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('json', models.JSONField()),
                ('profiles', models.ManyToManyField(to='security.profile')),
            ],
        ),
    ]
