"""Content Outline JSON Content

Revision ID: 13c8d451b7cd
Revises: 44038ed13371
Create Date: 2024-07-25 09:59:55.046920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13c8d451b7cd'
down_revision = '44038ed13371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_outline', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_outline', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
