"""ContentOutlines

Revision ID: 44038ed13371
Revises: 7f793573e57b
Create Date: 2024-07-24 14:49:24.655241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44038ed13371'
down_revision = '7f793573e57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_outline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_audience', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('wrote_as', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_outline', schema=None) as batch_op:
        batch_op.drop_column('content')
        batch_op.drop_column('additional_info')
        batch_op.drop_column('wrote_as')
        batch_op.drop_column('target_audience')

    # ### end Alembic commands ###
