"""Content ideas again

Revision ID: 7f793573e57b
Revises: 
Create Date: 2024-07-22 16:21:45.443241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f793573e57b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('topic_variation', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('topic_category', sa.String(length=200), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_idea', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('topic_category')
        batch_op.drop_column('topic_variation')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
